spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    url: jdbc:mysql://localhost:3306/amazon
    username: root
    password: Hareesha@190164
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081

  # appliaction messages goes here
auth-service :
  messages :
    userReg : User Created
    userRegError : User Creation Failed!
    login : Login Success
    loginError : Invalid Credentials
